version: '3'
services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - 5000:5000

  registry-ui:
    image: quiq/docker-registry-ui
    container_name: registry-ui
    volumes:
      - ./ui-config.yml:/opt/config.yml:ro
    ports:
      - 8000:8000
